### ISSUE TITLE
Getting a `HyTypeError` on load

### ISSUE THREAD

**Issue by callum-oakley** [hylang/vim-hy#16] opened 2018-04-08 10:54 UTC
`:python import hy` is all good, but when trying to load a `.hy` file with the plugin enabled I get

```
"awesome.hy" 1L, 67C
Error detected while processing function provider#python#Call:
line   18:
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/callum/.local/lib/python2.7/site-packages/hy/importer.py", line 240, in load_module
    return import_file_to_module(fullname, self.path, self)
  File "/home/callum/.local/lib/python2.7/site-packages/hy/importer.py", line 99, in import_file_to_module
    _ast = import_file_to_ast(fpath, module_name)
  File "/home/callum/.local/lib/python2.7/site-packages/hy/importer.py", line 57, in import_file_to_ast
    return hy_compile(import_file_to_hst(fpath), module_name)
  File "/home/callum/.local/lib/python2.7/site-packages/hy/compiler.py", line 2239, in hy_compile
    result = compiler.compile(tree)
  File "/home/callum/.local/lib/python2.7/site-packages/hy/compiler.py", line 460, in compile
    ret = self.compile_atom(_type, tree)
  File "/home/callum/.local/lib/python2.7/site-packages/hy/compiler.py", line 447, in compile_atom
    else _compile_table[atom_type](self, atom))
  File "/home/callum/.local/lib/python2.7/site-packages/hy/compiler.py", line 1738, in compile_expression
    ret = self.compile_atom(fn, expression)
  File "/home/callum/.local/lib/python2.7/site-packages/hy/compiler.py", line 447, in compile_atom
    else _compile_table[atom_type](self, atom))
  File "/home/callum/.local/lib/python2.7/site-packages/hy/compiler.py", line 819, in compile_do
    return self._compile_branch(expression)
  File "/home/callum/.local/lib/python2.7/site-packages/hy/compiler.py", line 545, in _compile_branch
    return _branch(self.compile(expr) for expr in exprs)
  File "/home/callum/.local/lib/python2.7/site-packages/hy/compiler.py", line 318, in _branch
    results = list(results)
  File "/home/callum/.local/lib/python2.7/site-packages/hy/compiler.py", line 545, in <genexpr>
    return _branch(self.compile(expr) for expr in exprs)
  File "/home/callum/.local/lib/python2.7/site-packages/hy/compiler.py", line 460, in compile
    ret = self.compile_atom(_type, tree)
  File "/home/callum/.local/lib/python2.7/site-packages/hy/compiler.py", line 447, in compile_atom
    else _compile_table[atom_type](self, atom))
  File "/home/callum/.local/lib/python2.7/site-packages/hy/compiler.py", line 1738, in compile_expression
    ret = self.compile_atom(fn, expression)
  File "/home/callum/.local/lib/python2.7/site-packages/hy/compiler.py", line 447, in compile_atom
    else _compile_table[atom_type](self, atom))
  File "/home/callum/.local/lib/python2.7/site-packages/hy/compiler.py", line 1800, in compile_def_expression
    return self._compile_assign(expression[0], expression[1])
  File "/home/callum/.local/lib/python2.7/site-packages/hy/compiler.py", line 1819, in _compile_assign
    result = self.compile(result)
  File "/home/callum/.local/lib/python2.7/site-packages/hy/compiler.py", line 460, in compile
    ret = self.compile_atom(_type, tree)
  File "/home/callum/.local/lib/python2.7/site-packages/hy/compiler.py", line 447, in compile_atom
    else _compile_table[atom_type](self, atom))
  File "/home/callum/.local/lib/python2.7/site-packages/hy/compiler.py", line 1738, in compile_expression
    ret = self.compile_atom(fn, expression)
  File "/home/callum/.local/lib/python2.7/site-packages/hy/compiler.py", line 447, in compile_atom
    else _compile_table[atom_type](self, atom))
  File "/home/callum/.local/lib/python2.7/site-packages/hy/compiler.py", line 372, in checker
    return fn(self, expression)
  File "/home/callum/.local/lib/python2.7/site-packages/hy/compiler.py", line 2007, in compile_function_def
    body = self._compile_branch(expression)
  File "/home/callum/.local/lib/python2.7/site-packages/hy/compiler.py", line 545, in _compile_branch
    return _branch(self.compile(expr) for expr in exprs)
  File "/home/callum/.local/lib/python2.7/site-packages/hy/compiler.py", line 318, in _branch
    results = list(results)
  File "/home/callum/.local/lib/python2.7/site-packages/hy/compiler.py", line 545, in <genexpr>
    return _branch(self.compile(expr) for expr in exprs)
  File "/home/callum/.local/lib/python2.7/site-packages/hy/compiler.py", line 460, in compile
    ret = self.compile_atom(_type, tree)
  File "/home/callum/.local/lib/python2.7/site-packages/hy/compiler.py", line 447, in compile_atom
    else _compile_table[atom_type](self, atom))
  File "/home/callum/.local/lib/python2.7/site-packages/hy/compiler.py", line 1781, in compile_expression
    func = self.compile(fn)
  File "/home/callum/.local/lib/python2.7/site-packages/hy/compiler.py", line 460, in compile
    ret = self.compile_atom(_type, tree)
  File "/home/callum/.local/lib/python2.7/site-packages/hy/compiler.py", line 447, in compile_atom
    else _compile_table[atom_type](self, atom))
  File "/home/callum/.local/lib/python2.7/site-packages/hy/compiler.py", line 1738, in compile_expression
    ret = self.compile_atom(fn, expression)
  File "/home/callum/.local/lib/python2.7/site-packages/hy/compiler.py", line 447, in compile_atom
    else _compile_table[atom_type](self, atom))
  File "/home/callum/.local/lib/python2.7/site-packages/hy/compiler.py", line 372, in checker
    return fn(self, expression)
  File "/home/callum/.local/lib/python2.7/site-packages/hy/compiler.py", line 2131, in compile_dispatch_tag_macro
    expr = tag_macroexpand(tag, expression.pop(0), self)
  File "/home/callum/.local/lib/python2.7/site-packages/hy/macros.py", line 226, in tag_macroexpand
    "`{0}' is not a defined tag macro.".format(tag)
HyTypeError:   File "/home/callum/.config/nvim/plugged/vim-hy/indent/hy_indent.hy", line 10, column 1
  (defn syn-id-attr [id attr]
  ^--------------------------
    (#v"synIDattr" id attr))
  -------------------------^
HyTypeError: `v' is not a defined tag macro.
```

`hy --version` is `hy 0.14.0+98.g096aac2`

This is in neovim if that makes a difference.

**Comment by epraw** [comment] 2018-07-01 18:42
This problem is caused by the [change in Hy 0.13 from defreader to deftag](http://docs.hylang.org/en/stable/language/api.html#deftag). This can be fixed by simply editing the definition of the reader macro v in line 4 of the last file mentioned in the traceback to be deftag instead of defreader.

**Closed** 2018-11-30 23:01 UTC
